### ISSUE TITLE
Request: RSS Feed Support for Tracking New Submissions

### ISSUE THREAD

**Issue by tillcash** [wdhdev/free-for-life#23]
I need the ability to track new submissions more efficiently. Currently, I have to manually check for updates, which is time-consuming. By implementing RSS feed support, I can easily subscribe to updates and receive notifications whenever new submissions are made. This feature would greatly enhance the usability and convenience of the platform.

Please have a look at https://github.com/trackawesomelist/trackawesomelist/ to gain some ideas.

**Comment by Jeymen** [comment]
@WilliamDavidHarrison Please take a look.

**Comment by WilliamDavidHarrison** [comment]
Sorry, I didn't see this issue show up in my notifications, thanks for mentioning me Jeymen. 

If you would like @tillcash I could create a new script which makes the service use JSON files for adding/removing services instead of multiple markdown files? Would that work?

Also, regarding trackawesomelist, I see they have a custom program for for automatically updating lists. Unfortunately, I do not have experience with Deno (the language they use) so I would not know how to set it up.

If you would like to discuss this further, please consider contacting me on Discord. My Discord username is [williamharrison](https://wdh.gg/discord).

**Comment by WilliamDavidHarrison** [comment]
May I ask what this implementation will be used for? I'm curious to know 😄

Also, may I know the JSON format you require?

**Comment by WilliamDavidHarrison** [comment]
I will consider adding this but I'm not sure when I will get to it as I am quite busy at the moment.

**Comment by Jeymen** [comment]
@WilliamDavidHarrison Are there any updates on this?

**Comment by WilliamDavidHarrison** [comment]
Not at the moment. I don't have the time to work on this, and the really only way this may get implemented is if someone else does it.

**Comment by Bocon778** [comment]
@wdhdev Any updates on this?

**Comment by wdhdev** [comment]
@Bocon778 Not really.

**Comment by VaibhavSys** [comment]
> @Bocon778 Not really.

I can pick this up.

**Comment by wdhdev** [comment]
@VaibhavSys That'd be great if you did. I'll assign you.
